= Configuración Inicial

== Instalación de dependencias
Debemos ubicarnos en la carpeta raiz, donde se encuentra el archivo package.json del proyecto (no confundir con el modulo) y ejecutar el siguiente comando
[source,shell script]
$ yarn install

[source,shell script]
#Respuesta
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 30.49s.

Dependiendo de la configuracion podrian tener un output mas verboso, validar que los 4 pasos se ejecutaron correctamente y que las posibles observaciones no detubieron el proceso.

== Configuración de cuenta AWS

Para este punto se debera tener un usuario de aws (**Programmatic access**)
Ejecutar el comando:
[source,shell script]
$ AWS configure

El comando preguntara por los siguientes valores

* AWS Access Key ID: Usuario programatico de aws, ejm: EDIAXVWRRT5YIDPLED42, no es el correo.
* AWS Secret Access Key: Clave del usuario
* Default region name: us-east-1
* Default output format: json

== Comandos para ejecutar el proyecto

=== Reformateo con prettier

Por un tema de estandares, se debe de usar el prettier para formatear su codigo, si es que la
integracion de prettier con su IDE no funciona.

[source,shell script]
----
$ yarn prettier
----

=== Pruebas unitarias

[source,shell script]
----
$ yarn lint
$ yarn test
----

=== Ejecucion OffLine / Local

Para poder realizar pruebas sobre las funciones que se construyeron, el proyecto tiene la capacidad de ejecutarse en local.
Para ello ejecutar el comando serverless offiline con el nombre del modulo (nombre que figura en el package.json del modulo)

[source, shell script]
----
$ yarn workspace transaction-api serverless offline
----

=== Deploy & Destroy

[source, shell script]
----
$ yarn workspace transaction-api serverless deploy --stage dev
$ yarn workspace transaction-api serverless remove --stage dev
----
